Successful LilyPond build.
This is a rebased and updated version of

  https://github.com/gperciva/gub/pull/7

condensed into a single commit.

* *.make: Use $(GUB) and $(PYTHON) instead of `bin/gub' and `python',
  respectively.
* bin/gib: Print help message if run without arguments.
* bin/gub: Remove unnecessary lambda.
* gub/dependency.py: Avoid
    TypeError: issubclass() arg 1 must be a class.
* gcc.py, guile.py: Don't build info docs.
* lilypond-doc.py, lilypond-test.py: Don't run `dblatex' regression tests.